!!org.chaostocosmos.net.tcp.Config
adminPassword: null
adminPort: 9393
adminUser: null
proxyHost: localhost
sessionMapping:
  InnoQuartz:
    allowedHosts: []
    keepAlive: true
    proxyPort: 1212
    receiveBufferSize: 0
    remoteHost: prod.innoquartz.net
    remotePort: 9090
    sendBufferSize: 0
    soTimeout: 0
    tcpNoDelay: true
  Oracle:
    allowedHosts: [192.168.1.1, 127.0.0.1]
    keepAlive: true
    proxyPort: 5555
    receiveBufferSize: 0
    remoteHost: 192.168.1.157
    remotePort: 1521
    sendBufferSize: 0
    soTimeout: 0
    tcpNoDelay: true
  MySQL:
    allowedHosts: [192.168.1.2, 127.0.0.1]
    keepAlive: true
    proxyPort: 2323
    receiveBufferSize: 0
    remoteHost: 192.168.1.157
    remotePort: 9336
    sendBufferSize: 0
    soTimeout: 0
    tcpNoDelay: true


                                             
