adminPassword: null
adminPort: 9292
adminUser: null
forbiddenRemote: [
  ]
proxyHost: localhost
sessionMapping:
  MySQL:
    allowedHosts: [127.0.0.1]
    threadPoolCoreSize: 10
    threadPoolMaxSize: 50
    threadPoolIdleSecond: 600
    threadPoolQueueSize: 30
    bufferSize: 0
    connectionTimeout: 3
    keepAlive: false
    proxyBindAddress: localhost
    proxyPort: 1212
    remoteHosts: [192.168.1.157:1521]
    sessionMode: STAND_ALONE
    standAloneRetry: 3
    loadBalanceRatio: 
    failedCircularRetry: 3
    soTimeout: 0
    tcpNoDelay: false
  Kafka:
    allowedHosts: [127.0.0.1]
    threadPoolCoreSize: 10
    threadPoolMaxSize: 50
    threadPoolIdleSecond: 600
    threadPoolQueueSize: 30
    bufferSize: 0
    connectionTimeout: 0
    keepAlive: false
    proxyBindAddress: localhost
    proxyPort: 1213
    remoteHosts: [192.168.1.152:8092]
    sessionMode: STAND_ALONE
    standAloneRetry: 3
    loadBalanceRatio: 
    failedCircularRetry: 3
    soTimeout: 0
    tcpNoDelay: false
  Oracle:
    allowedHosts: [127.0.0.1]
    threadPoolCoreSize: 10
    threadPoolMaxSize: 50
    threadPoolIdleSecond: 600
    threadPoolQueueSize: 30
    bufferSize: 0
    connectionTimeout: 3
    keepAlive: false
    proxyBindAddress: localhost
    proxyPort: 1214
    remoteHosts: [192.168.1.157:1522, 192.168.1.155:9090, 192.168.1.157:1521, 192.168.1.157:1521]
    sessionMode: LOAD_BALANCE_SEPARATE_RATIO
    standAloneRetry: 3
    loadBalanceRatio: 10:20:30:50
    failedCircularRetry: 6
    soTimeout: 0
    tcpNoDelay: false

